### ISSUE TITLE
Webpack production config isn't working

### ISSUE THREAD

**Issue by dkh215** [dkh215/django-react-redux-template#1]
When debug=false in settings.py, the correct js bundle isn't loading. 

<img width="679" alt="screen shot 2016-07-25 at 12 46 42 pm" src="https://cloud.githubusercontent.com/assets/16489251/17109638/cf9ed3c2-5266-11e6-98e2-c56d7c9e96b4.png">

When debug=true, I'm able to link to the correct js file.

![screen shot 2016-07-25 at 12 51 27 pm](https://cloud.githubusercontent.com/assets/16489251/17109657/e870173a-5266-11e6-98a9-235be7cf6509.png)

I haven't figured out how to get the static paths correct for production.  I think my STATIC_ROOT, STATIC_URL and webpack prod config settings aren't aligning properly.

@sburns Could you have a look?

**Comment by dkh215** [comment]
Hey @sburns, just circling back to this.  Any thoughts?  Thanks!

**Comment by sburns** [comment]
My apologies. I've got a working directory with most things working but need to put some commits together. The biggest thing I saw was the "omniview" you set up in urls.py was catching *all* requests including things at `/static/...`.

**Comment by dkh215** [comment]
Ok cool no worries, thanks again!

**Comment by dkh215** [comment]
@sburns ok I think I'm super close 👍 

I updated urls.py but still getting this error when debug=false:

<img width="1264" alt="screen shot 2016-08-25 at 7 54 23 am" src="https://cloud.githubusercontent.com/assets/16489251/17968247/bdb1ceda-6a99-11e6-8a72-40c5ff11df12.png">

**Comment by dkh215** [comment]
Got it, had to update my STATIC_URL.

**Comment by sburns** [comment]
I meant to say earlier, it's most likely one of your `STATIC*` settings :)
